### ISSUE TITLE
[WinInstaller] Not crashing, but stuck

### ISSUE THREAD

**Issue by Bluscream** [iVEnoVaLue/BetterPlugins#1]
![image](https://cloud.githubusercontent.com/assets/3318223/14514744/bb01d892-01f3-11e6-8f6e-46ae5a163dd9.png)

It's not crashing but still not installing anything :o

**Comment by iVEnoVaLue** [comment]
When Discord is open, it can't delete used folders

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/14514896/1ccc1302-01f5-11e6-9693-63a9a63d4ac7.png)
I dont see Discord*.exe anywhere here.

**Comment by iVEnoVaLue** [comment]
try deleting %localappdata%/Discord/app-0.0.287/resources/app folder 
if it fails you know why. some app keeps it open

**Comment by Bluscream** [comment]
Yeah got it working thanks :)
